In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
# soorting
a = np.array([7, 2, 4, 1, 6, 5])

sorted_a = np.sort(a)
print(sorted_a)


[1 2 4 5 6 7]


In [13]:
# Slicing=> [start: end: step]
# [::1] -> from start to last and step is 1
# [::-1] -> from start to last but step is -1 so, it will be reversed

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# print(arr)

print(arr[1, 1:4])

[7 8 9]


In [15]:
# slice both of the nested array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [18]:
# print only the column
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print( 'the column of index 1:', arr[:, 1])

the column of index 1: [2 7]


In [19]:
# print only the row
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print( 'the row of index 1:', arr[1, :])

the row of index 1: [ 6  7  8  9 10]
